### ISSUE TITLE
Backup process

### ISSUE THREAD

**Issue by huydhoang** [akhil-naidu/t2d#14]
Hi, I've just installed forem using your bash script today, and was surprised by how automated it could be.
You really have done an amazing job. Congrats!
But I'm wondering how to properly backup/restore forem data in case it's needed to migrate or reinstall.
Can you please provide some instructions?

**Comment by akhil-naidu** [comment]
I tried to do my best to incorporate most things, but there are always some limitations with scripting and automating. For now, the only solution is to use your s3 bucket for backup and restore. 

To highlight many such issues, I'm creating a web application. It is not yet ready, but backup and restore are tightly integrated within it. You can see the dashboard at https://selfhost.dev

> I'm actively working on the project, and as I'm the only one working on this, it might take a while.

**Comment by huydhoang** [comment]
Thank you. I greatly appreciate your effort at making the web based solution.
However, concerning your own investment in the project, I must say it's not an easy road to take. People who want self hosting are often either on a budget, behind a firewall /security paranoid, or both. They wouldn't easily give you access to their cloud VM if your code's not open source. Opening source can devalue your code but gives you the advantage of building trust with customers to sell a service. Otherwise, you should consider partnering with the DEV creators themselves to somehow integrate this into their cloud solution / or just buy their front page ads.
I wish you all the best!
