### ISSUE TITLE
Forem doesn't have a mount volume for the images

### ISSUE THREAD

**Issue by patrickdronk** [akhil-naidu/t2d#15]
When updating forem, the images dissapear. This is probably because there isn't a mount to a volume right or am I missing something?

**Comment by akhil-naidu** [comment]
Yes, there is no concept of mounting volume in Forem and t2d; that is one of the main reasons I usually recommend using the s3 bucket as storage.

This way, even if you want to migrate to an entirely new server, all of your assets are saved with the added benefit of backing up your Postgres Database regularly.
